### PR TITLE
Add CHANGELOG

### PR DESCRIPTION
**Pull request by rubo77**
Created from git with 

```
git log --after=2013-01-12 --no-merges |grep -v -E '(Author|commit|Caelers)'|head -n 10000|sed 's/Date:\s*//g'|sed 's/\+0.00//g'>CHANGELOG
```

### CODE REVIEW

**Comment by rubo77** [comment]
Maybe you can edit the commit a bit to add the point releases in bold

**Comment by Justinzobel** [comment]
This would be nice. A summary (user understandable) of each release.

**Comment by mattia-b89** [comment]
I think this is no more needed due to github.com features: _commit_ and _release_ tabs give us the same results

**Comment by rubo77** [comment]
It would be nice to have a **maintained** Changelog.

My initial Idea was only to add the current history as a start, from then on, you could maintain it by hand, when features are added.

The commit-tab in github is not really useful, because it only shows 10 commits per page, you cannot search  there

**Comment by mattia-b89** [comment]
I do not understand well your need:
- there is a *NEWS* file which states in human readable way the changes
- there are github.com feature which can list _all_ commits e.g. from the *release* tab you can list all commits from today until latest-release date [https://github.com/rcaelers/workrave/compare/v1_10_37...branch_v1_10]

**Comment by rubo77** [comment]
Ah OK!!! the NEWS file is a CHANGELOG, that was missing for me!!!

you should rename the NEWS file to CHANGELOG then!

this is more of a standard

**Comment by Justinzobel** [comment]
Alternatively create a symlink to NEWS called CHANGELOG.

**Comment by matkoniecz** [comment]
Maybe it would be a good idea to close it rather than keeping indefinitely? Not processed PR from 2015 is a bit silly.

**Comment by rcaelers** [comment]
Indeed. Let's close this one. Workrave keeps an overview of user-visible changes in the NEWS file, per [GNU standard](https://www.gnu.org/prep/standards/html_node/NEWS-File.html#NEWS-File).

**Pull request closed without merging**
