### PR TITLE
Add new Bells sound theme

### PR DESCRIPTION
**Pull request by pieterdd**
These are sound effects I've created myself, so I have the legal authority to grant Workrave a license to use them.

### CODE REVIEW

**Comment by pieterdd** [comment]
I'm not familiar with this repo or Makefiles for that matter. Could you tell me why my build is failing and how I can fix it?

```
Making all in sounds
make[5]: Entering directory '/workspace/source/frontend/common/share/sounds'
Making all in bells
make[6]: *** No rule to make target 'all'.  Stop.
make[6]: Entering directory '/workspace/source/frontend/common/share/sounds/bells'
make[6]: Leaving directory '/workspace/source/frontend/common/share/sounds/bells'
Makefile:493: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
```

**Comment by rcaelers** [comment]
Thanks for the contribution!

You also need to update the configure.ac file:

AC_CONFIG_FILES([Makefile
             backend/Makefile
...
             frontend/common/share/sounds/Makefile
             frontend/common/share/sounds/subtle/Makefile
             frontend/common/share/sounds/default/Makefile

**Comment by pieterdd** [comment]
Nice, that worked. There's one remaining build failure though. Pulled from the logs:

```
/usr/bin/install: cannot create regular file '/workspace/source/workrave-1.10.44/_inst/share/workrave/exercises/exercises.xml': File exists
```

Any chance this is unrelated to my changes?

**Comment by rcaelers** [comment]
> Any chance this is unrelated to my changes?

No. It seems the exercises.xml file gets installed twice. I'm not sure why it did not cause any issues before....
Should be fixed now.

**Comment by pieterdd** [comment]
Perfect. Thanks for helping me fix the build!

**Comment by rcaelers** [comment]
Thanks again! I will add your name to credit.h file later.
Until a new release is available, you can download a development build for Windows at https://workrave.org/snapshots/

**Comment by pieterdd** [comment]
I just had a chance to boot up my Windows machine and try the latest snapshot. Is it possible that I still need to take an additional action to add it to the dropdown menu?

image

I think I assumed it would populate automatically based on the presence of the sound theme file.

**Comment by rcaelers** [comment]
Oops. I forgot to update the installer configuration file.... Should be fixed in the latest snapshot.
I have also added your name to the credits list (in About window)

**Pull request merged**
