### PR TITLE
Overhaul of zh-CN.po

### PR DESCRIPTION
**Pull request by sr093906**
I localized zh_CN.po from scratch based on https://github.com/rcaelers/workrave/blob/main/po/workrave.pot

### CODE REVIEW

**Comment by rcaelers** [comment]
Thanks! Please have a look at the failed builds:
/workspace/source/po/zh_CN.po:1022:12: syntax error
/workspace/source/po/zh_CN.po:1023: end-of-line within string
/usr/bin/msgfmt: found 2 fatal errors

**Comment by sr093906** [comment]
@rcaelers 

Thanks for pointing that out. Tests are ongoing. But I believe they will finish without error. Please have a look later.

**Comment by greyovo** [comment]
https://github.com/rcaelers/workrave/blob/7da3584b050d10307883008be716d5e95e643ce7/po/zh_CN.po#L703

line 702：
```po
#: ui/apps/gtkmm/src/PreludeWindow.cc:104
msgid "Time for a micro-break?"
msgstr "小憩的持续时间？"
```

@sr093906  我觉得此处的原翻译 "暂停一下？" 会更合适，这个 time for 应该是“该做什么”的意思吧

**Comment by sr093906** [comment]
@greyovo Will revise it. Thanks.

**Pull request merged**
