### PR TITLE
Improve locking the screen and shutting down, introduce suspend/hibernate

### PR DESCRIPTION
**Pull request by matjon**
Hello,
I have written some code to enable suspending and hibernating the machine from rest break and daily limit windows. This has been a feature I have always missed in Workrave.
By the way I have also improved greatly support for locking the screen and shutting down.
All these things should now work correctly on most Linux installations currently in use.

Please review.
Greetings,
Mateusz Jończyk

### CODE REVIEW

**Comment by elmerehbi** [comment]
Hi there,

I am writing here because I couldn't find and "issue" section to open a new issue.

On several occasions my system was suspended during a rest break. Does this have to do with workrave without the user's interaction?

**Comment by rcaelers** [comment]
What version of Workrave are you using? This sounds like a bug that was fixed in 1.10.14.

**Comment by elmerehbi** [comment]
Version 1.10.10.0 from Ubuntu's repos. Is there a ppa?

**Comment by rcaelers** [comment]
Yes: https://launchpad.net/~rob-caelers/+archive/ubuntu/workrave

**Comment by elmerehbi** [comment]
@rcaelers Thanks.

**Comment by sebix** [comment]
@elmerehbi http://issues.workrave.org/ (linked at the website workrave.org, not sure if this bugtracker is still active)

**Pull request merged**
