### PR TITLE
Add a python script that executes an external bash script on microbreak ...

### PR DESCRIPTION
**Pull request by rubo77**
...start and another on successfull completion of the microbreak without postpone/Skip

### CODE REVIEW

**Comment by rubo77** [comment]
This makes workrave depending on https://github.com/rubo77/mouse-speed, feel free to include this in your project

**Comment by rubo77** [comment]
can we somehow re-anable this?

related: https://github.com/rcaelers/workrave/issues/105

**Comment by buscon** [comment]
I would be happy to help adding this feature, I can program in python. But I don't understand how mouse-speed relates to this feature.

**Comment by rubo77** [comment]
I want to call the mouse speed script on each done and not-done Microbreak

**Comment by rcaelers** [comment]
Hi. The script is in the contrib/mouse-speed/ directory.  As far as I know the DBUS interface hasn't changed. So it should still work. if not, please let me know

**Comment by xerus2000** [comment]
hey, I'd love an update on this as well :)

**Pull request merged**
